# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\NOBLEWARRIOR29\Desktop\MY_FILES\DOCS_PROG\sample_prog\project_graph\new_python_graph\scratch.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 675)
        MainWindow.setMinimumSize(QtCore.QSize(769, 675))
        MainWindow.setMaximumSize(QtCore.QSize(769, 675))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logos/Untitled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{    font-family: century gothic;\n"
"font-size:17px;\n"
"background: #35424a;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton\n"
"{\n"
"border-radius:60px;\n"
"background: #e8491d;\n"
"transition: 0.9s ease;\n"
"font-size:13px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: white;\n"
"color: #000;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background: transparent;\n"
"border: none;\n"
"color: #ffffff;\n"
"border-bottom: 1px solid #717072\n"
"}\n"
"QComboBox\n"
"{\n"
"background:#333;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    selection-background-color: #333;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_vertex_container = QtWidgets.QFrame(self.centralwidget)
        self.add_vertex_container.setGeometry(QtCore.QRect(10, 100, 281, 111))
        self.add_vertex_container.setStyleSheet("")
        self.add_vertex_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_vertex_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_vertex_container.setObjectName("add_vertex_container")
        self.lineedit_vertex = QtWidgets.QLineEdit(self.add_vertex_container)
        self.lineedit_vertex.setGeometry(QtCore.QRect(0, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineedit_vertex.setFont(font)
        self.lineedit_vertex.setMaxLength(1)
        self.lineedit_vertex.setObjectName("lineedit_vertex")
        self.label = QtWidgets.QLabel(self.add_vertex_container)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pb_add_vertex = QtWidgets.QPushButton(self.add_vertex_container)
        self.pb_add_vertex.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.pb_add_vertex.setFont(font)
        self.pb_add_vertex.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_add_vertex.setObjectName("pb_add_vertex")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 60, 291, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("alternate-background-color: rgb(51, 51, 51);")
        self.comboBox.setObjectName("comboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logos/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/logos/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logos/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/logos/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/logos/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, "")
        self.add_edge_container = QtWidgets.QFrame(self.centralwidget)
        self.add_edge_container.setGeometry(QtCore.QRect(10, 100, 281, 111))
        self.add_edge_container.setStyleSheet("")
        self.add_edge_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_edge_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_edge_container.setObjectName("add_edge_container")
        self.lineedit_edge_two = QtWidgets.QLineEdit(self.add_edge_container)
        self.lineedit_edge_two.setGeometry(QtCore.QRect(0, 50, 281, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineedit_edge_two.setFont(font)
        self.lineedit_edge_two.setMaxLength(1)
        self.lineedit_edge_two.setObjectName("lineedit_edge_two")
        self.label_3 = QtWidgets.QLabel(self.add_edge_container)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pb_add_edge = QtWidgets.QPushButton(self.add_edge_container)
        self.pb_add_edge.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.pb_add_edge.setFont(font)
        self.pb_add_edge.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_add_edge.setObjectName("pb_add_edge")
        self.lineedit_edge_one = QtWidgets.QLineEdit(self.add_edge_container)
        self.lineedit_edge_one.setGeometry(QtCore.QRect(0, 20, 281, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineedit_edge_one.setFont(font)
        self.lineedit_edge_one.setMaxLength(1)
        self.lineedit_edge_one.setObjectName("lineedit_edge_one")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 60, 441, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(10, 100, 281, 111))
        self.container.setStyleSheet("")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.label_6 = QtWidgets.QLabel(self.container)
        self.label_6.setGeometry(QtCore.QRect(60, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.disply_container = QtWidgets.QFrame(self.centralwidget)
        self.disply_container.setGeometry(QtCore.QRect(10, 200, 261, 101))
        self.disply_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.disply_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disply_container.setObjectName("disply_container")
        self.label_8 = QtWidgets.QLabel(self.disply_container)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rb_show_ttb = QtWidgets.QRadioButton(self.disply_container)
        self.rb_show_ttb.setGeometry(QtCore.QRect(10, 40, 211, 16))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.rb_show_ttb.setFont(font)
        self.rb_show_ttb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_show_ttb.setObjectName("rb_show_ttb")
        self.rb_show_bfs = QtWidgets.QRadioButton(self.disply_container)
        self.rb_show_bfs.setGeometry(QtCore.QRect(10, 60, 211, 17))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.rb_show_bfs.setFont(font)
        self.rb_show_bfs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_show_bfs.setObjectName("rb_show_bfs")
        self.rb_show_dfs = QtWidgets.QRadioButton(self.disply_container)
        self.rb_show_dfs.setGeometry(QtCore.QRect(10, 80, 171, 17))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.rb_show_dfs.setFont(font)
        self.rb_show_dfs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rb_show_dfs.setObjectName("rb_show_dfs")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(300, 100, 461, 461))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background: #35424a;\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 320, 281, 241))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, 300, 81, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pb_delete_all = QtWidgets.QPushButton(self.centralwidget)
        self.pb_delete_all.setGeometry(QtCore.QRect(150, 520, 121, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.pb_delete_all.setFont(font)
        self.pb_delete_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_delete_all.setObjectName("pb_delete_all")
        self.BFS_container = QtWidgets.QFrame(self.centralwidget)
        self.BFS_container.setGeometry(QtCore.QRect(10, 100, 281, 111))
        self.BFS_container.setStyleSheet("")
        self.BFS_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BFS_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BFS_container.setObjectName("BFS_container")
        self.lineedit_bfs = QtWidgets.QLineEdit(self.BFS_container)
        self.lineedit_bfs.setGeometry(QtCore.QRect(0, 30, 281, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineedit_bfs.setFont(font)
        self.lineedit_bfs.setMaxLength(1)
        self.lineedit_bfs.setObjectName("lineedit_bfs")
        self.label_10 = QtWidgets.QLabel(self.BFS_container)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 191, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pb_bfs = QtWidgets.QPushButton(self.BFS_container)
        self.pb_bfs.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.pb_bfs.setFont(font)
        self.pb_bfs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_bfs.setObjectName("pb_bfs")
        self.DFS_container = QtWidgets.QFrame(self.centralwidget)
        self.DFS_container.setGeometry(QtCore.QRect(10, 100, 281, 111))
        self.DFS_container.setStyleSheet("pb_dfs{\n"
"border: 1px solid white;\n"
"    padding: 10px 30px;\n"
"    text-decoration: none;\n"
"    color: white;    \n"
"    transition: 0.6s ease;\n"
"border-raduis:60px;\n"
"}")
        self.DFS_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DFS_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DFS_container.setObjectName("DFS_container")
        self.lineedit_dfs = QtWidgets.QLineEdit(self.DFS_container)
        self.lineedit_dfs.setGeometry(QtCore.QRect(0, 30, 281, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineedit_dfs.setFont(font)
        self.lineedit_dfs.setMaxLength(1)
        self.lineedit_dfs.setObjectName("lineedit_dfs")
        self.label_11 = QtWidgets.QLabel(self.DFS_container)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 161, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pb_dfs = QtWidgets.QPushButton(self.DFS_container)
        self.pb_dfs.setGeometry(QtCore.QRect(180, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.pb_dfs.setFont(font)
        self.pb_dfs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_dfs.setObjectName("pb_dfs")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(230, 10, 331, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background: #e8491d;")
        self.label_14.setObjectName("label_14")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -30, 881, 71))
        self.label_2.setStyleSheet("background: #e8491d;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-50, 30, 931, 16))
        self.label_4.setStyleSheet("background-color: #333;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 590, 131, 21))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(340, 580, 47, 41))
        self.label_12.setStyleSheet("border-image: url(:/logos/pc.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 540, 171, 111))
        self.label_13.setStyleSheet("border-image: url(:/logos/logo.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(460, 570, 51, 51))
        self.label_15.setStyleSheet("border-image: url(:/logos/css.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(500, 570, 81, 71))
        self.label_16.setStyleSheet("border-image: url(:/logos/bootsrap.png);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(-30, 640, 911, 61))
        self.label_17.setStyleSheet("background: #e8491d;")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(280, 640, 241, 31))
        self.label_18.setStyleSheet("background: #e8491d;\n"
"font-size:15px;\n"
"")
        self.label_18.setObjectName("label_18")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 771, 681))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.frame.setFont(font)
        self.frame.setStyleSheet("*\n"
"{\n"
"font-family: century gothic;\n"
"\n"
"background: #35424a;\n"
"color: #ffffff;\n"
"padding: 0;\n"
"margin: 0;\n"
"font-size:20px;\n"
"}\n"
"QProgressBar {\n"
"     border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #ffffff;\n"
"font-size:1px;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #045FB4;\n"
"     width: 5px;\n"
" }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(30, 630, 711, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(300, 590, 281, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(200, 130, 401, 291))
        self.label_20.setStyleSheet("border-image: url(:/logos/logo.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(270, 590, 21, 31))
        self.label_21.setStyleSheet("border-image: url(:/logos/Untitled.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(280, 350, 291, 51))
        self.label_22.setObjectName("label_22")
        self.label_13.raise_()
        self.label_16.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.disply_container.raise_()
        self.listWidget.raise_()
        self.listWidget_2.raise_()
        self.label_9.raise_()
        self.pb_delete_all.raise_()
        self.DFS_container.raise_()
        self.label_14.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_7.raise_()
        self.BFS_container.raise_()
        self.container.raise_()
        self.add_edge_container.raise_()
        self.add_vertex_container.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Graph Data Stucture"))
        self.lineedit_vertex.setPlaceholderText(_translate("MainWindow", "Enter Element here"))
        self.label.setText(_translate("MainWindow", "ADD VERTEX"))
        self.pb_add_vertex.setText(_translate("MainWindow", "add vertex"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose Action"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Add Vertex"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Add Edge"))
        self.comboBox.setItemText(3, _translate("MainWindow", "BFS Traversal"))
        self.comboBox.setItemText(4, _translate("MainWindow", "DFS Traversal"))
        self.lineedit_edge_two.setPlaceholderText(_translate("MainWindow", "Enter 2nd vertex"))
        self.label_3.setText(_translate("MainWindow", "ADD EDGE"))
        self.pb_add_edge.setText(_translate("MainWindow", "add edge"))
        self.lineedit_edge_one.setPlaceholderText(_translate("MainWindow", "Enter 1st vertex"))
        self.label_7.setText(_translate("MainWindow", "EDGE TRUTH TABLE - BFS TRAVERSAL - DFS TRAVERSAL"))
        self.label_6.setText(_translate("MainWindow", "CHOOSE ACTION"))
        self.label_8.setText(_translate("MainWindow", "DISPLAY:"))
        self.rb_show_ttb.setText(_translate("MainWindow", "EDGE TRUTH TABLE"))
        self.rb_show_bfs.setText(_translate("MainWindow", "BFS TRAVERSAL"))
        self.rb_show_dfs.setText(_translate("MainWindow", "DFS TRAVERSAL"))
        self.label_9.setText(_translate("MainWindow", "VERTICES"))
        self.pb_delete_all.setText(_translate("MainWindow", "Delete all Vertex"))
        self.lineedit_bfs.setPlaceholderText(_translate("MainWindow", "Enter Element here"))
        self.label_10.setText(_translate("MainWindow", "BFS TRAVERSAL"))
        self.pb_bfs.setText(_translate("MainWindow", "OK"))
        self.lineedit_dfs.setPlaceholderText(_translate("MainWindow", "Enter Element here"))
        self.label_11.setText(_translate("MainWindow", "DFS TRAVERSAL"))
        self.pb_dfs.setText(_translate("MainWindow", "OK"))
        self.label_14.setText(_translate("MainWindow", "GRAPH DATA STRUCTURE (UNDIRECTED)"))
        self.label_5.setText(_translate("MainWindow", "Powered by"))
        self.label_18.setText(_translate("MainWindow", "Wiball Dev™ | Copyright 2019 ©"))
        self.label_19.setText(_translate("MainWindow", "Initializing Environment..."))
        self.label_22.setText(_translate("MainWindow", "# Hello World, Goodbye."))
import pics


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
